fixed filepath bug
tscircuit/v0.0.x-cli pull request #212
Opened 2024-09-26 14:16 UTC by ShiboSoftwareDev

there are two new issues:
- api\tests\routes\export_requests\list.test.ts timed out but works if you increase timeout to 10k ms
- I can't export anything maybe I think the problem is in the file: run-entrypoint-file.ts

2024-09-26 16:01 UTC, seveibar commented
We can increase the timeout for the test inside the workflow (not a big deal) do you want to make that edit to see if the tests pass? I didn't understand your other issue, the diff is a bit hard to read because of a formatting issue, maybe you could run `bun run format`

2024-09-27 22:08 UTC, seveibar commented on cli/lib/soupify/run-entrypoint-file.ts
> +      console.log(e)
hmm we should probably revert this part because it silences errors

2024-09-27 22:10 UTC, seveibar requested changes
looking good, some minor tweaks and this is ready to ship!

2024-09-27 22:10 UTC, seveibar commented on cli/lib/soupify/run-entrypoint-file.ts
> +      console.log(e)
*continuing after errors

2024-09-27 22:10 UTC, seveibar commented on cli/lib/soupify/run-entrypoint-file.ts
> +  try {
do we need this big try catch here?

2024-09-27 22:10 UTC, seveibar commented on cli/lib/soupify/soupify-with-core.ts
> +    import React from "react"
it's actually correct here to not have indentation, the output file is going to have a lot of indentation if we add indentation here

2024-09-27 22:12 UTC, ShiboSoftwareDev commented on cli/lib/soupify/run-entrypoint-file.ts
> +  try {
I forgot to remove these

2024-09-27 22:16 UTC, ShiboSoftwareDev commented on cli/lib/soupify/soupify-with-core.ts
> +    import React from "react"
I'll reverse this change

2024-09-28 15:12 UTC, seveibar commented on cli/lib/export-fns/export-gerbers.ts
> +  console.log(soup, "soup")
```suggestion
```

2024-09-28 15:12 UTC, seveibar commented on cli/lib/export-fns/export-gerbers.ts
> +  console.log("step two")
```suggestion
```

2024-09-28 15:12 UTC, seveibar commented on cli/lib/export-fns/export-gerbers.ts
> +  console.log("step last")
```suggestion
```

2024-09-28 15:12 UTC, seveibar commented on cli/lib/soupify/run-entrypoint-file.ts
> +    .stdout(debug.enabled ? "inheritPiped" : "piped")
Hmm why remove noThrow here?

2024-09-28 15:21 UTC, seveibar approved these changes

2024-09-28 15:21 UTC, ShiboSoftwareDev commented
@seveibar I used to review my own code I don't why I stopped doing that, sorry for that

2024-09-28 15:22 UTC, seveibar commented
@ShiboSoftwareDev all good, we should enable a lint rule for console log lines anyway so that its not easy to leave them in- i think biome has a setting

2024-09-28 15:23 UTC, merged